### ISSUE TITLE
Bug: When trying to run the smoke tests by being in a user home workspace, tests fail

### ISSUE THREAD

**Issue by kasturinarra** [kcp-dev/kcp-tests#12]
### What version of Go are you using (`go version`)?

<pre>
$ go version
[knarra@knarra kcp-tests]$ go version
go version go1.18.1 linux/amd64

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What version of oc are you using (`oc version`)?

<pre>
$ oc version

</pre>

### What did you run?
[knarra@knarra kcp-tests]$ ./bin/kcp-tests run all --dry-run | grep "Multi levels workspaces lifecycle should work" | ./bin/kcp-tests run -f -
INFO Sep 20 21:46:53.878: serverURL is 
INFO Sep 20 21:46:54.891: Error running /bin/kubectl get workspace/~ --server= -o=jsonpath={.status.URL}:
Error from server (NotFound): clusterworkspaces.tenancy.kcp.dev "~" not found
INFO Sep 20 21:46:54.891: Getting home workspace server failed: "exit status 1"

[knarra@knarra kcp-tests]$ kubectl kcp ws .
Current workspace is "root:users:lw:ao:rh-sso-knarrakcp".

### What did you expect to see?

Let us make sure that tests do not fail and it works irrespective of where the user is currently

**Comment by kasturinarra** [comment]
@Phaow can you check and see if we can fix this ? If you are not sure of what the error is we could discuss on thursday as i am on PTO tomorrow, thanks !!

**Comment by Phaow** [comment]
> @Phaow can you check and see if we can fix this ? If you are not sure of what the error is we could discuss on thursday as i am on PTO tomorrow, thanks !!

Sure, I think it's not a bug of framework, I replied on slack. It seems I need to add some descriptions to README enhance it.

**Comment by Phaow** [comment]
Fix: **[kcp-dev/kcp-tests/pull/14](https://github.com/kcp-dev/kcp-tests/pull/14)**

**Comment by kasturinarra** [comment]
closing the issue as the PR above has been merged.
